import React, { useState, useEffect } from 'react';
import { LogOut, BarChart2, Download, RefreshCw } from 'lucide-react';
import { MapContainer, TileLayer, CircleMarker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import { logout } from '../firebase';
import NotificationBell from './NotificationBell';
import QRGenerator from './QRGenerator';

interface ReportData {
  period: { from: string; to: string };
  totalTickets: number;
  closedTickets: number;
  slaBreaches: number;
  redFlags: number;
  majorOverhauls: number;
  categoryBreakdown: Record<string, number>;
  iowStats: Record<string, { total: number; closed: number; breached: number; name?: string }>;
}

// Pure browser PDF report generator
function generateDefaulterReport(report: ReportData) {
  const iowRows = Object.entries(report.iowStats)
    .sort((a, b) => b[1].breached - a[1].breached)
    .map(([pf, s]) => `  ${(s.name || pf).padEnd(30)} | ${String(s.total).padEnd(8)} | ${String(s.closed).padEnd(8)} | ${String(s.breached).padEnd(10)} | ${s.total > 0 ? Math.round((s.closed / s.total) * 100) : 0}%`)
    .join('\n');

  const catRows = Object.entries(report.categoryBreakdown)
    .sort((a, b) => b[1] - a[1])
    .map(([cat, count]) => `  ${cat.padEnd(28)} : ${count} complaints`)
    .join('\n');

  const content = `
══════════════════════════════════════════════════════════════════
          MONTHLY PERFORMANCE REPORT — RailAwaas Care
                   Indian Railways Quarter Wing
══════════════════════════════════════════════════════════════════

GENERATED ON : ${new Date().toLocaleString('en-IN')}
PERIOD       : ${new Date(report.period.from).toLocaleDateString('en-IN')} to ${new Date(report.period.to).toLocaleDateString('en-IN')}

──────────────────────────────────────────────────────────────────
EXECUTIVE SUMMARY
──────────────────────────────────────────────────────────────────
  Total Complaints Received   : ${report.totalTickets}
  Successfully Closed         : ${report.closedTickets} (${report.totalTickets > 0 ? Math.round((report.closedTickets / report.totalTickets) * 100) : 0}%)
  SLA Breaches (Active)       : ${report.slaBreaches}
  Red-Flag Escalations        : ${report.redFlags}
  Major Overhaul Flagged      : ${report.majorOverhauls}

──────────────────────────────────────────────────────────────────
CATEGORY-WISE BREAKDOWN
──────────────────────────────────────────────────────────────────
${catRows || '  No data available'}

──────────────────────────────────────────────────────────────────
IOW PERFORMANCE SCORECARD (DEFAULTER LIST)
──────────────────────────────────────────────────────────────────
  ${'IOW Name'.padEnd(30)} | ${'Total'.padEnd(8)} | ${'Closed'.padEnd(8)} | ${'Breached'.padEnd(10)} | Rate
  ${'-'.repeat(70)}
${iowRows || '  No IOW data available'}

──────────────────────────────────────────────────────────────────
ACTION ITEMS
──────────────────────────────────────────────────────────────────
  1. IOWs with >3 SLA breaches to be issued show-cause notice.
  2. Tickets flagged Red for >7 days to be escalated to ADRM.
  3. Major Overhaul quarters to be inspected by Divisional Engineer.

══════════════════════════════════════════════════════════════════
  This report is auto-generated by RailAwaas Care System.
  All records are blockchain-audited and tamper-proof.
  Reference: RAIL-RPT-${Date.now().toString().slice(-8)}
══════════════════════════════════════════════════════════════════
  `.trim();

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `RailAwaas_MonthlyReport_${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function DRMDashboard({ user, onLogout }: { user: any; onLogout: () => void }) {
  const [tickets, setTickets] = useState<any[]>([]);
  const [report, setReport] = useState<ReportData | null>(null);
  const [heatmap, setHeatmap] = useState<any[]>([]);
  const [loadingReport, setLoadingReport] = useState(false);
  const [activeTab, setActiveTab] = useState<'overview' | 'map' | 'report' | 'qr'>('overview');

  useEffect(() => {
    fetchTickets();
    fetchHeatmap();
  }, []);

  const fetchTickets = async () => {
    const res = await fetch('/api/tickets?role=DRM');
    const data = await res.json();
    if (data.success) setTickets(data.tickets);
  };

  const fetchHeatmap = async () => {
    const res = await fetch('/api/reports/heatmap');
    const data = await res.json();
    if (data.success) setHeatmap(data.heatmapData);
  };

  const fetchReport = async () => {
    setLoadingReport(true);
    const res = await fetch('/api/reports/monthly');
    const data = await res.json();
    if (data.success) setReport(data.report);
    setLoadingReport(false);
  };

  const handleDownloadReport = async () => {
    if (!report) await fetchReport();
    if (report) generateDefaulterReport(report);
  };

  const redTickets    = tickets.filter(t => t.flag_color === 'Red').length;
  const orangeTickets = tickets.filter(t => t.flag_color === 'Orange').length;
  const openTickets   = tickets.filter(t => t.status !== 'Closed').length;
  const closedToday   = tickets.filter(t => t.status === 'Closed' && t.closed_at && new Date(t.closed_at).toDateString() === new Date().toDateString()).length;
  const majorOverhaulCount = tickets.filter(t => t.major_overhaul).length;

  // Category breakdown for chart
  const catBreak: Record<string, number> = {};
  tickets.forEach(t => { catBreak[t.category] = (catBreak[t.category] || 0) + 1; });
  const catMax = Math.max(...Object.values(catBreak), 1);

  // IOW performance
  const iowPerf: Record<string, { open: number; overdue: number }> = {};
  tickets.forEach(t => {
    if (!t.assigned_iow) return;
    if (!iowPerf[t.assigned_iow]) iowPerf[t.assigned_iow] = { open: 0, overdue: 0 };
    if (t.status !== 'Closed') iowPerf[t.assigned_iow].open++;
    if (new Date(t.SLA_deadline) < new Date() && t.status !== 'Closed') iowPerf[t.assigned_iow].overdue++;
  });

  const STAT_CARDS = [
    { label: 'Total Tickets', value: tickets.length, color: '#1a56db', bg: '#eff6ff', icon: '🎫' },
    { label: 'Open Now', value: openTickets, color: '#d97706', bg: '#fffbeb', icon: '⏳' },
    { label: '🔴 Red Flags', value: redTickets, color: '#dc2626', bg: '#fef2f2', icon: '🔴' },
    { label: 'Closed Today', value: closedToday, color: '#10b981', bg: '#ecfdf5', icon: '✅' },
    { label: 'Major Overhauls', value: majorOverhaulCount, color: '#7c3aed', bg: '#f5f3ff', icon: '🏚️' },
    { label: '🟠 Orange', value: orangeTickets, color: '#f97316', bg: '#fff7ed', icon: '🟠' },
  ];

  return (
    <div style={{ minHeight: '100vh', background: '#f1f5f9', display: 'flex', flexDirection: 'column' }}>
      {/* Header */}
      <header className="bg-drm-header" style={{ padding: '12px 24px', boxShadow: '0 2px 12px rgba(0,0,0,0.25)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', maxWidth: 1400, margin: '0 auto' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
            <div style={{ width: 44, height: 44, background: 'linear-gradient(135deg, #1a56db, #3730a3)', borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 4px 12px rgba(26,86,219,0.4)' }}>
              <BarChart2 size={22} color="white" />
            </div>
            <div>
              <h1 style={{ margin: 0, fontSize: 18, fontWeight: 900, color: 'white', letterSpacing: '-0.3px' }}>DRM Command Centre</h1>
              <p style={{ margin: 0, fontSize: 11, color: '#94a3b8' }}>RailAwaas Care · Division: {user.hq || 'Central'} · {user.name}</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
            <button onClick={fetchTickets} style={{ background: 'rgba(255,255,255,0.08)', border: 'none', borderRadius: 10, padding: 9, cursor: 'pointer', color: '#94a3b8', display: 'flex' }}>
              <RefreshCw size={16} />
            </button>
            <NotificationBell userPf={user.pf_no} />
            <button onClick={() => { logout(); onLogout(); }} style={{ background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.15)', borderRadius: 10, padding: '8px 14px', cursor: 'pointer', color: 'white', display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, fontWeight: 600 }}>
              <LogOut size={15} /> Logout
            </button>
          </div>
        </div>
      </header>

      {/* Tabs */}
      <div style={{ background: '#0f172a', padding: '0 24px', borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
        <div style={{ display: 'flex', gap: 0, maxWidth: 1400, margin: '0 auto' }}>
          {[
            { id: 'overview', label: '📊 Overview' },
            { id: 'map', label: '🗺️ Heatmap' },
            { id: 'report', label: '📋 Report' },
            { id: 'qr', label: '⬡ QR Tools' },
          ].map(tab => (
            <button key={tab.id} onClick={() => { setActiveTab(tab.id as any); if (tab.id === 'report' && !report) fetchReport(); }}
              style={{ padding: '12px 18px', background: 'transparent', border: 'none', cursor: 'pointer', fontSize: 13, fontWeight: activeTab === tab.id ? 700 : 500, color: activeTab === tab.id ? 'white' : '#64748b', borderBottom: `2px solid ${activeTab === tab.id ? '#1a56db' : 'transparent'}`, transition: 'all 0.2s', whiteSpace: 'nowrap' }}>
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      <main style={{ flex: 1, padding: '20px 24px', maxWidth: 1400, margin: '0 auto', width: '100%' }}>

        {/* OVERVIEW */}
        {activeTab === 'overview' && (
          <div className="animate-fade-in">
            {/* Stats Grid */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 14, marginBottom: 24 }}>
              {STAT_CARDS.map(s => (
                <div key={s.label} style={{ background: 'white', borderRadius: 16, padding: '18px 20px', border: '1px solid #e2e8f0', boxShadow: '0 1px 4px rgba(0,0,0,0.06)', transition: 'all 0.2s' }}
                  onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 8px 24px rgba(0,0,0,0.1)'; }}
                  onMouseLeave={e => { e.currentTarget.style.transform = ''; e.currentTarget.style.boxShadow = '0 1px 4px rgba(0,0,0,0.06)'; }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                    <div>
                      <p style={{ margin: '0 0 6px', fontSize: 11, fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{s.label}</p>
                      <p style={{ margin: 0, fontSize: 36, fontWeight: 900, color: s.color, letterSpacing: '-1px' }}>{s.value}</p>
                    </div>
                    <div style={{ width: 48, height: 48, background: s.bg, borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 22 }}>{s.icon}</div>
                  </div>
                </div>
              ))}
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
              {/* Category Bar Chart */}
              <div style={{ background: 'white', borderRadius: 16, border: '1px solid #e2e8f0', padding: '18px 20px' }}>
                <h3 style={{ margin: '0 0 16px', fontSize: 14, fontWeight: 700, color: '#1e293b' }}>📊 Complaints by Category</h3>
                <div className="bar-chart-container">
                  {Object.entries(catBreak).map(([cat, count]) => (
                    <div key={cat} className="bar-item">
                      <span style={{ fontSize: 11, fontWeight: 700, color: '#1a56db' }}>{count}</span>
                      <div className="bar-fill" style={{
                        height: `${(count / catMax) * 90}px`,
                        background: cat === 'Civil' ? 'linear-gradient(#1a56db,#3730a3)' : cat === 'Electrical' ? 'linear-gradient(#f59e0b,#d97706)' : cat === 'Sanitary' ? 'linear-gradient(#10b981,#059669)' : cat === 'Carpentry' ? 'linear-gradient(#8b5cf6,#7c3aed)' : 'linear-gradient(#ec4899,#db2777)',
                      }} />
                      <span style={{ fontSize: 9, color: '#94a3b8', textAlign: 'center', lineHeight: 1.2 }}>{cat}</span>
                    </div>
                  ))}
                  {Object.keys(catBreak).length === 0 && <p style={{ color: '#94a3b8', fontSize: 13, margin: 'auto' }}>No data yet</p>}
                </div>
              </div>

              {/* SLA Breach by IOW */}
              <div style={{ background: 'white', borderRadius: 16, border: '1px solid #e2e8f0', padding: '18px 20px' }}>
                <h3 style={{ margin: '0 0 16px', fontSize: 14, fontWeight: 700, color: '#1e293b' }}>🚨 SLA Breaches by IOW</h3>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                  {Object.entries(iowPerf).length === 0 ? (
                    <p style={{ color: '#94a3b8', fontSize: 13 }}>No IOW performance data yet.</p>
                  ) : (
                    Object.entries(iowPerf).sort((a, b) => b[1].overdue - a[1].overdue).map(([pf, perf]) => (
                      <div key={pf}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                          <span style={{ fontSize: 12, fontWeight: 600, color: '#374151' }}>{pf}</span>
                          <span style={{ fontSize: 12, color: perf.overdue > 0 ? '#dc2626' : '#10b981', fontWeight: 700 }}>{perf.overdue} breached</span>
                        </div>
                        <div style={{ height: 6, background: '#f1f5f9', borderRadius: 999 }}>
                          <div style={{ height: '100%', borderRadius: 999, width: `${perf.open > 0 ? Math.min(100, (perf.overdue / perf.open) * 100) : 0}%`, background: perf.overdue > 2 ? '#ef4444' : perf.overdue > 0 ? '#f97316' : '#10b981', transition: 'width 0.5s ease' }} />
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>

            {/* Recent Red-Flag Tickets */}
            <div style={{ background: 'white', borderRadius: 16, border: '1px solid #fecaca', marginTop: 16, overflow: 'hidden' }}>
              <div style={{ padding: '14px 18px', background: '#fef2f2', borderBottom: '1px solid #fecaca', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <h3 style={{ margin: 0, fontSize: 14, fontWeight: 700, color: '#991b1b' }}>🔴 Red-Flag Escalations (Immediate Attention)</h3>
                <span style={{ fontSize: 12, color: '#dc2626', fontWeight: 700 }}>{redTickets} tickets</span>
              </div>
              {tickets.filter(t => t.flag_color === 'Red').slice(0, 5).map(t => (
                <div key={t.id} style={{ padding: '12px 18px', borderBottom: '1px solid #fef2f2', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <span style={{ fontWeight: 600, fontSize: 13, color: '#1e293b' }}>#{t.id} · {t.category} — {t.sub_category}</span>
                    <p style={{ margin: 0, fontSize: 11, color: '#94a3b8' }}>PF: {t.pf_no} · SLA due: {new Date(t.SLA_deadline).toLocaleDateString('en-IN')}</p>
                  </div>
                  <span style={{ fontSize: 10, fontWeight: 700, color: '#dc2626', background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 4, padding: '2px 8px' }}>
                    +{Math.round((Date.now() - new Date(t.SLA_deadline).getTime()) / 3600000)}h OVERDUE
                  </span>
                </div>
              ))}
              {redTickets === 0 && <div style={{ padding: '20px 18px', color: '#94a3b8', fontSize: 13 }}>No red-flag tickets. Division is in good health! ✅</div>}
            </div>
          </div>
        )}

        {/* MAP */}
        {activeTab === 'map' && (
          <div className="animate-fade-in" style={{ background: 'white', borderRadius: 16, border: '1px solid #e2e8f0', overflow: 'hidden', height: 550 }}>
            <div style={{ padding: '14px 18px', borderBottom: '1px solid #f1f5f9', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <h3 style={{ margin: 0, fontSize: 14, fontWeight: 700, color: '#1e293b' }}>🗺️ Complaint Heatmap — Live GPS Data</h3>
              <div style={{ display: 'flex', gap: 10, alignItems: 'center', fontSize: 11 }}>
                <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}><span style={{ width: 10, height: 10, borderRadius: '50%', background: '#ef4444', display: 'inline-block' }} /> Red (3+)</span>
                <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}><span style={{ width: 10, height: 10, borderRadius: '50%', background: '#f97316', display: 'inline-block' }} /> Orange (2)</span>
                <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}><span style={{ width: 10, height: 10, borderRadius: '50%', background: '#22c55e', display: 'inline-block' }} /> Green (1)</span>
              </div>
            </div>
            <MapContainer center={[28.6139, 77.209]} zoom={13} style={{ height: 'calc(100% - 56px)', width: '100%' }}>
              <TileLayer url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />
              {heatmap.map((p, i) => (
                <CircleMarker
                  key={i}
                  center={[p.lat, p.lng]}
                  radius={14}
                  pathOptions={{
                    color: p.flag === 'Red' ? '#ef4444' : p.flag === 'Orange' ? '#f97316' : '#22c55e',
                    fillColor: p.flag === 'Red' ? '#ef4444' : p.flag === 'Orange' ? '#f97316' : '#22c55e',
                    fillOpacity: 0.7,
                    weight: 2,
                  }}
                >
                  <Popup>
                    <div style={{ fontFamily: 'Inter, sans-serif', fontSize: 12 }}>
                      <strong>{p.quarter}</strong><br />
                      Flag: <strong style={{ color: p.flag === 'Red' ? '#dc2626' : '#f97316' }}>{p.flag || 'None'}</strong>
                    </div>
                  </Popup>
                </CircleMarker>
              ))}
            </MapContainer>
          </div>
        )}

        {/* REPORT */}
        {activeTab === 'report' && (
          <div className="animate-fade-in">
            <div style={{ background: 'white', borderRadius: 16, border: '1px solid #e2e8f0', overflow: 'hidden' }}>
              <div style={{ padding: '20px 24px', background: 'linear-gradient(135deg, #0f172a, #1e293b)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                  <h3 style={{ margin: 0, fontSize: 16, fontWeight: 800, color: 'white' }}>📋 Monthly Defaulter Report</h3>
                  <p style={{ margin: '4px 0 0', fontSize: 12, color: '#94a3b8' }}>Last 30 days performance — auto-compiled from blockchain records</p>
                </div>
                <button onClick={() => { if (report) generateDefaulterReport(report); else fetchReport().then(() => report && generateDefaulterReport(report!)); }} disabled={loadingReport} className="btn-primary" style={{ width: 'auto', padding: '10px 18px' }}>
                  <Download size={14} /> {loadingReport ? 'Generating...' : 'Download Report'}
                </button>
              </div>

              {loadingReport ? (
                <div style={{ padding: 40, textAlign: 'center', color: '#94a3b8' }}>
                  <div style={{ width: 32, height: 32, border: '3px solid #e2e8f0', borderTopColor: '#1a56db', borderRadius: '50%', margin: '0 auto 12px', animation: 'spin-slow 1s linear infinite' }} />
                  <p style={{ margin: 0 }}>Compiling report from audit ledger...</p>
                </div>
              ) : report ? (
                <div style={{ padding: 24 }}>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 20 }}>
                    {[
                      { label: 'Total', value: report.totalTickets, color: '#1a56db' },
                      { label: 'Closed', value: report.closedTickets, color: '#10b981' },
                      { label: 'SLA Breaches', value: report.slaBreaches, color: '#f97316' },
                      { label: 'Red Flags', value: report.redFlags, color: '#dc2626' },
                    ].map(s => (
                      <div key={s.label} style={{ background: '#f8fafc', borderRadius: 12, padding: '12px 14px', textAlign: 'center' }}>
                        <p style={{ margin: 0, fontSize: 28, fontWeight: 800, color: s.color }}>{s.value}</p>
                        <p style={{ margin: 0, fontSize: 11, color: '#64748b', fontWeight: 600 }}>{s.label}</p>
                      </div>
                    ))}
                  </div>

                  <h4 style={{ margin: '0 0 12px', fontSize: 13, fontWeight: 700, color: '#1e293b' }}>IOW Defaulter Scorecard</h4>
                  {Object.keys(report.iowStats).length === 0 ? (
                    <p style={{ color: '#94a3b8', fontSize: 13 }}>No IOW assignment data available for this period.</p>
                  ) : (
                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                      <thead>
                        <tr style={{ background: '#f8fafc' }}>
                          {['IOW Name / PF', 'Total', 'Closed', 'Breached', 'Rate'].map(h => (
                            <th key={h} style={{ padding: '8px 12px', textAlign: 'left', fontSize: 11, fontWeight: 700, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.06em', borderBottom: '1px solid #e2e8f0' }}>{h}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {Object.entries(report.iowStats).sort((a, b) => b[1].breached - a[1].breached).map(([pf, s]) => (
                          <tr key={pf} style={{ borderBottom: '1px solid #f8fafc' }}>
                            <td style={{ padding: '10px 12px', fontWeight: 600, color: '#1e293b' }}>{s.name || pf}</td>
                            <td style={{ padding: '10px 12px', color: '#1a56db', fontWeight: 700 }}>{s.total}</td>
                            <td style={{ padding: '10px 12px', color: '#10b981', fontWeight: 700 }}>{s.closed}</td>
                            <td style={{ padding: '10px 12px' }}>
                              <span style={{ fontWeight: 700, color: s.breached > 3 ? '#dc2626' : s.breached > 0 ? '#f97316' : '#10b981' }}>{s.breached}</span>
                              {s.breached > 3 && <span style={{ marginLeft: 6, fontSize: 10, color: '#dc2626', fontWeight: 700, background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 4, padding: '1px 5px' }}>DEFAULTER</span>}
                            </td>
                            <td style={{ padding: '10px 12px', fontWeight: 700, color: s.total > 0 && (s.closed / s.total) > 0.8 ? '#10b981' : '#f97316' }}>
                              {s.total > 0 ? Math.round((s.closed / s.total) * 100) : 0}%
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              ) : (
                <div style={{ padding: 40, textAlign: 'center', color: '#94a3b8' }}>
                  <p style={{ margin: '0 0 12px', fontSize: 32 }}>📊</p>
                  <p style={{ margin: 0, fontSize: 14 }}>Report will load automatically...</p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* QR TOOLS */}
        {activeTab === 'qr' && (
          <div className="animate-fade-in" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
            <div style={{ background: 'white', borderRadius: 16, border: '1px solid #e2e8f0', overflow: 'hidden' }}>
              <QRGenerator />
            </div>
            <div style={{ background: 'white', borderRadius: 16, border: '1px solid #e2e8f0', padding: 24 }}>
              <h3 style={{ margin: '0 0 12px', fontSize: 14, fontWeight: 700, color: '#1e293b' }}>📋 QR Code Usage Guide</h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {[
                  { step: '1', title: 'Generate QR for Quarter', desc: 'Enter the quarter number, type, and GPS coordinates. Auto-detect GPS for accuracy.' },
                  { step: '2', title: 'Print & Affix', desc: 'Download the QR PNG and print it. Affix to the main door of the quarter.' },
                  { step: '3', title: 'Employee Scans', desc: 'Employee opens RailAwaas Care app → Home → "Scan QR". Complaint form auto-fills with quarter details.' },
                  { step: '4', title: 'Geo-Fence Activated', desc: 'IOW must be within 50m of the GPS coordinates in the QR to mark the ticket as Resolved.' },
                ].map(item => (
                  <div key={item.step} style={{ display: 'flex', gap: 12, padding: '10px 12px', background: '#f8fafc', borderRadius: 10 }}>
                    <div style={{ width: 28, height: 28, borderRadius: '50%', background: '#1a56db', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontWeight: 700, flexShrink: 0 }}>{item.step}</div>
                    <div>
                      <p style={{ margin: '0 0 2px', fontSize: 13, fontWeight: 700, color: '#1e293b' }}>{item.title}</p>
                      <p style={{ margin: 0, fontSize: 12, color: '#64748b', lineHeight: 1.5 }}>{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
