import React, { useState } from 'react';
import { X, AlertCircle, FileText } from 'lucide-react';

interface Props {
  ticketId: number;
  ticket: {
    id: number;
    category: string;
    sub_category: string;
    description: string;
  };
  iow: { name: string; pf_no: string };
  onClose: () => void;
  onSuccess: () => void;
}

const HOLD_REASONS = [
  'Cement / Concrete Mix Not Available',
  'GI / CPVC Pipes & Fittings Out of Stock',
  'Electrical Wires & MCB Unavailable',
  'Ceramic / Vitrified Tiles Not Available',
  'Hardware & Fittings (Locks, Hinges) Missing',
  'Paint & Primer Stock Depleted',
  'Skilled Labour / Contractor Not Available',
  'Other Material (Specify in Description)',
];

// Pure browser-based PDF generation using Canvas (no external lib needed)
function generateMaterialIndentPDF(data: {
  ticketId: number;
  category: string;
  subCategory: string;
  reason: string;
  iowName: string;
  iowPf: string;
  date: string;
}) {
  // Create a formatted text content for the PDF (downloaded as .txt with formatting)
  // When jsPDF is installed, swap this with proper PDF
  const content = `
══════════════════════════════════════════════════════
         MATERIAL INDENT SLIP — RailAwaas Care
          Indian Railways Quarter Maintenance
══════════════════════════════════════════════════════

INDENT REFERENCE : IND-${data.ticketId}-${Date.now().toString().slice(-6)}
DATE & TIME      : ${data.date}
STATUS           : PENDING APPROVAL FROM SSE

──────────────────────────────────────────────────────
TICKET DETAILS
──────────────────────────────────────────────────────
Ticket ID        : #${data.ticketId}
Category         : ${data.category}
Sub-Category     : ${data.subCategory}

──────────────────────────────────────────────────────
MATERIAL REQUIRED
──────────────────────────────────────────────────────
Reason for Hold  : ${data.reason}

──────────────────────────────────────────────────────
IOW DETAILS
──────────────────────────────────────────────────────
IOW Name         : ${data.iowName}
PF Number        : ${data.iowPf}

──────────────────────────────────────────────────────
SIGNATURES
──────────────────────────────────────────────────────
IOW Signature    : ____________________   Date: ________

SSE Signature    : ____________________   Date: ________

══════════════════════════════════════════════════════
This document is system-generated by RailAwaas Care.
Blockchain Hash will be appended upon SSE approval.
══════════════════════════════════════════════════════
  `.trim();

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `MaterialIndent_Ticket${data.ticketId}_${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function MaterialIndentModal({ ticketId, ticket, iow, onClose, onSuccess }: Props) {
  const [reason, setReason] = useState('');
  const [loading, setLoading] = useState(false);
  const [step, setStep] = useState<'form' | 'success'>('form');

  const handleSubmit = async () => {
    if (!reason) return;
    setLoading(true);
    try {
      const res = await fetch(`/api/tickets/${ticketId}/hold`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ pf_no: iow.pf_no, hold_reason: reason }),
      });
      const data = await res.json();
      if (data.success) {
        // Generate & download indent PDF
        generateMaterialIndentPDF({
          ticketId,
          category: ticket.category,
          subCategory: ticket.sub_category,
          reason,
          iowName: iow.name,
          iowPf: iow.pf_no,
          date: new Date().toLocaleString('en-IN'),
        });
        setStep('success');
        setTimeout(() => { onSuccess(); }, 2000);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="modal-overlay">
      <div className="modal-box">
        {/* Header */}
        <div style={{ background: 'linear-gradient(135deg, #f97316, #ea580c)', padding: '20px 20px 16px', color: 'white' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                <AlertCircle size={20} />
                <h3 style={{ margin: 0, fontSize: 16, fontWeight: 700 }}>Mark Pending-Material</h3>
              </div>
              <p style={{ margin: 0, fontSize: 12, opacity: 0.9 }}>Ticket #{ticketId} · {ticket.category} - {ticket.sub_category}</p>
            </div>
            <button onClick={onClose} style={{ background: 'rgba(255,255,255,0.2)', border: 'none', borderRadius: 8, padding: 6, cursor: 'pointer', color: 'white' }}>
              <X size={16} />
            </button>
          </div>
        </div>

        <div style={{ padding: 20 }}>
          {step === 'form' ? (
            <>
              <div style={{ background: '#fffbeb', border: '1px solid #fde68a', borderRadius: 10, padding: '10px 14px', marginBottom: 16, fontSize: 12, color: '#92400e' }}>
                ⚠️ Selecting this will pause the SLA timer and auto-generate a <strong>Material Indent PDF</strong> sent to SSE.
              </div>

              <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: '#374151', marginBottom: 8 }}>
                Select Material Required *
              </label>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 20 }}>
                {HOLD_REASONS.map(r => (
                  <label key={r} style={{
                    display: 'flex', alignItems: 'flex-start', gap: 10, padding: '10px 14px',
                    border: `1.5px solid ${reason === r ? '#f97316' : '#e2e8f0'}`,
                    borderRadius: 10, cursor: 'pointer',
                    background: reason === r ? '#fff7ed' : 'white',
                    transition: 'all 0.15s',
                  }}>
                    <input
                      type="radio" name="hold_reason" value={r}
                      checked={reason === r}
                      onChange={() => setReason(r)}
                      style={{ marginTop: 2, accentColor: '#f97316' }}
                    />
                    <span style={{ fontSize: 13, color: '#374151', lineHeight: 1.4 }}>{r}</span>
                  </label>
                ))}
              </div>

              <div style={{ display: 'flex', gap: 10 }}>
                <button onClick={onClose} className="btn-ghost" style={{ flex: 1 }}>Cancel</button>
                <button
                  onClick={handleSubmit}
                  disabled={!reason || loading}
                  className="btn-amber"
                  style={{ flex: 2 }}
                >
                  {loading ? '⏳ Processing...' : '📄 Submit & Generate Indent'}
                </button>
              </div>
            </>
          ) : (
            <div className="animate-scale-in" style={{ textAlign: 'center', padding: '20px 0' }}>
              <div style={{ width: 64, height: 64, background: '#f0fdf4', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>
                <FileText size={28} color="#10b981" />
              </div>
              <h4 style={{ margin: '0 0 8px', color: '#1e293b', fontSize: 16, fontWeight: 700 }}>Indent Generated!</h4>
              <p style={{ margin: 0, color: '#64748b', fontSize: 13 }}>
                Material Indent PDF downloaded. SSE has been notified automatically.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
